version: "3"

services:
  densyy-node-server:
    image: "densyy/densyy-node-server"
    build: "./"
    restart: always
    volumes:
      - "/volumes/densyy-node-server/:/host/densyy-node-server/"
    network_mode: "host"
